In [1]:
import numpy as np


In [2]:
q1 = np.array([
    [200,220,250],    # Product A
    [150, 180, 210],  # Product B
    [300, 330, 360]   # Product C
])

q2 = np.array([
    [209, 231, 259],  # Product A
    [155, 192, 222],  # Product B
    [310, 340, 375]   # Product C
])

In [3]:
# combined sales of Q1 and Q2
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [4]:
# sales units growth in q2 compared to q1
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [5]:
# % sales units growth in q2 compared to q1
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [6]:
prices = np.array([
    [10, 12, 11],  # Prices for Product A in different regions
    [8,  9,  10],  # Prices for Product B
    [15, 16, 17]   # Prices for Product C
])

q1_revenue = q1 * prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [7]:
q1_discounts = q1_revenue*0.02
q1_discounts

array([[ 40. ,  52.8,  55. ],
       [ 24. ,  32.4,  42. ],
       [ 90. , 105.6, 122.4]])

In [8]:
net_revenue = q1_revenue - q1_discounts
net_revenue

array([[1960. , 2587.2, 2695. ],
       [1176. , 1587.6, 2058. ],
       [4410. , 5174.4, 5997.6]])

In [9]:
np.sum(q1_discounts)

564.2

In [10]:
# first column is square footage, second is bedrooms
features = np.array([
    [2000, 3], # house 1
    [1800, 2]  # house 2
])

weights = np.array([150, 50000])

price = np.dot(features, weights)
price

array([450000, 370000])

In [11]:
c = np.array([1,2,3])
d = np.array([4,5,6])
np.cross(c,d)

array([-3,  6, -3])