In [1]:
import torch

In [2]:
units = torch.tensor([
    [200, 220],  # Product A (iPhone)
    [150, 180],  # Product B (iPad)
    [300, 330]   # Product C (MacBook)
])

In [3]:
units.shape

torch.Size([3, 2])

In [4]:
units.dtype

torch.int64

In [5]:
units.device

device(type='cpu')

In [6]:
## Tensor Reshaping

In [7]:
units.view(-1)

tensor([200, 220, 150, 180, 300, 330])

In [8]:
units.view(2,3)

tensor([[200, 220, 150],
        [180, 300, 330]])

In [9]:
units.view(6,1)

tensor([[200],
        [220],
        [150],
        [180],
        [300],
        [330]])

In [10]:
units

tensor([[200, 220],
        [150, 180],
        [300, 330]])

In [11]:
units[2,0]

tensor(300)

In [12]:
units[2,0] = 305
units

tensor([[200, 220],
        [150, 180],
        [305, 330]])

In [13]:
## Creating tensors with Specific Values

In [14]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.ones((3,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [20]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [21]:
torch.rand((3,5))

tensor([[0.4936, 0.7516, 0.1478, 0.0411, 0.3471],
        [0.6314, 0.1054, 0.5132, 0.6276, 0.6336],
        [0.9209, 0.8051, 0.7471, 0.7901, 0.9812]])